channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal==5.31.1
  - bbmap==38.58
  - skesa==2.4.0
  - pip
  - pip:
    - jsonschema>=4.18.0a1
    - numpy==1.21.5
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - bifrostlib
    - -e .
