channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal==5.31.1
  - bbmap==38.58
  - skesa==2.4.0
  - minimap2==2.17
  - samtools==1.14 #from 1.11 updated to 1.14 because it was incompatible
  - cyvcf2==0.30.14 #from 0.30.1 updated to 0.30.14 because it was incompatible
  - pip
  - pip:
    - jsonschema<4
    - warlock==1.3.3
    - quast==5.2.0
    - numpy==1.21.5
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - bifrostlib